### ISSUE TITLE
Downgrading T230T with latest bios

### ISSUE THREAD

**Issue by exander77** [dpolitis/auto-1vyprep#2]
I have Set Flash BIOS Updating by End-Users to Enabled, and Secure RollBack Prevention to Disabled, but I get:
```
ERROR 234 - SecureFlash verification fail!
```

**Comment by exander77** [comment]
Seems like I cannot rollback below 2.68 bios. Release notes:
```
If the UEFI BIOS has been updated to version 2.68 or higher, it is no longer able to roll back to the version before 2.68 for security improment.
```
So this seems to pretty limit use of this tool.

**Comment by dpolitis** [comment]
Not really tested if it is doable to downgrade if you updated your bios. You can always use the links in the repo files to download and flash a vulnerable bios version using a pomona clip.
