### ISSUE TITLE
But what if I use Linux?

### ISSUE THREAD

**Issue by Heidegaff** [dpolitis/auto-1vyprep#3]
I don't have Windows installed on my machine. How can I run auto-1vyprep?

**Comment by dpolitis** [comment]
You do not really need a running windows system. You only need a windows 10 iso. You can find detailed info in the README file. You can also find a win10 iso to use from here:
https://software-download.microsoft.com/download/pr/19041.264.200511-0456.vb_release_svc_refresh_CLIENTENTERPRISEEVAL_OEMRET_x64FRE_en-us.iso

Closing this, as it is not a software issue.
